x-variables:
    flag_initial_cluster_token: &flag_initial_cluster_token '--initial-cluster-token=mys3cr3ttok3n'
    common_settings: &common_settings
#        image: quay.io/coreos/etcd:v3.5.16
        image: model.vnet.com/zhongzi/etcd:v3.5.16
        entrypoint: /usr/local/bin/etcd
        ports:
            - 2379

services:
    etcd-1:
        <<: *common_settings
        command:
            - '--name=etcd-1'
            - '--initial-advertise-peer-urls=http://etcd-1:2380'
            - '--listen-peer-urls=http://0.0.0.0:2380'
            - '--listen-client-urls=http://0.0.0.0:2379'
            - '--advertise-client-urls=http://etcd-1:2379'
            - '--heartbeat-interval=250'
            - '--election-timeout=1250'
            - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
            - '--initial-cluster-state=new'
            - *flag_initial_cluster_token
        volumes:
            - etcd1:/etcd_data
        networks:
          - etcd

    etcd-2:
        <<: *common_settings
        command:
            - '--name=etcd-2'
            - '--initial-advertise-peer-urls=http://etcd-2:2380'
            - '--listen-peer-urls=http://0.0.0.0:2380'
            - '--listen-client-urls=http://0.0.0.0:2379'
            - '--advertise-client-urls=http://etcd-2:2379'
            - '--heartbeat-interval=250'
            - '--election-timeout=1250'
            - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
            - '--initial-cluster-state=new'
            - *flag_initial_cluster_token
        volumes:
            - etcd2:/etcd_data
        networks:
          - etcd

    etcd-3:
        <<: *common_settings
        command:
            - '--name=etcd-3'
            - '--initial-advertise-peer-urls=http://etcd-3:2380'
            - '--listen-peer-urls=http://0.0.0.0:2380'
            - '--listen-client-urls=http://0.0.0.0:2379'
            - '--advertise-client-urls=http://etcd-3:2379'
            - '--heartbeat-interval=250'
            - '--election-timeout=1250'
            - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
            - '--initial-cluster-state=new'
            - *flag_initial_cluster_token
        volumes:
            - etcd3:/etcd_data
        networks:
          - etcd

    nginx:
      image: model.vnet.com/zhongzi/nginx:1.21.6-alpine-perl
      hostname: nginx-etcd
      volumes:
        - type: bind
          source: ./nginx/nginx.conf
          target: /etc/nginx/nginx.conf
      networks:
        - etcd
      ports:
        - 2379:2379
      depends_on:
        - etcd-1
        - etcd-2
        - etcd-3
      logging:
        driver: "json-file"
        options:
          max-size: "1m"
          max-file: "5"
      restart: always

    etcd-workbench:
      image: tzfun/etcd-workbench:latest
      container_name: etcd-workbench
      ports:
        - "8002:8002"
      volumes:
        - "./etcd-workbench.conf:/usr/tzfun/etcd-workbench/etcd-workbench.conf"
      restart: unless-stopped

volumes:
    etcd1:
      driver: local
      driver_opts:
        type: none
        device: ${PWD}/etcd1
        o: bind
    etcd2:
      driver: local
      driver_opts:
        type: none
        device: ${PWD}/etcd2
        o: bind
    etcd3:
      driver: local
      driver_opts:
        type: none
        device: ${PWD}/etcd3
        o: bind
networks:
  etcd:
    driver: bridge