#Compose目前有三个版本分别为Version 1，Version 2，Version 3，Compose区分Version 1和Version 2（Compose 1.6.0+，Docker Engine 1.10.0+）。Version 2支持更多的指令。Version 1将来会被弃用。

version: "2"

services:

  # 服务名称

  redis-7000:

    # 服务的镜像名称或镜像ID。如果镜像在本地不存在，Compose将会尝试拉取镜像。

    image: model.vnet.com/zhongzi/redis:6.2.6-alpine

    # 创建的容器名称

    container_name: redis-7000

    # 自启动

    restart: always

    # container内的root拥有真正的root权限。否则，container内的root只是外部的一个普通用户权限。

    privileged: true

    # 为容器设置环境变量：

    environment:

      - TZ=Asia/Shanghai

    # 端口映射，格式为宿主机端口:容器内部端口

    ports:

      - "7000:7000"

      - "17000:17000"

    # 注意：这里记得打开集群总线端口，规则为offset 10000 - "17000:17000",容器内部就是通过17000这个端口进行连接的

    # 挂载数据卷，用于宿主机和容器共享文件，格式为宿主机目录:容器内部目录

    volumes:
      - ./data/7000:/data
      - ./cluster-config/redis-node-7000.conf:/usr/local/etc/redis/redis.conf

    # 覆盖容器启动后默认执行的命令。

    command: redis-server /usr/local/etc/redis/redis.conf




  redis-7001:

    # 服务的镜像名称或镜像ID。如果镜像在本地不存在，Compose将会尝试拉取镜像。

    image: model.vnet.com/zhongzi/redis:6.2.6-alpine

    # 创建的容器名称

    container_name: redis-7001

    # 自启动

    restart: always

    # container内的root拥有真正的root权限。否则，container内的root只是外部的一个普通用户权限。

    privileged: true

    # 为容器设置环境变量：

    environment:

      - TZ=Asia/Shanghai

    # 端口映射，格式为宿主机端口:容器内部端口

    ports:

      - "7001:7001"

      - "17001:17001"

    # 注意：这里记得打开集群总线端口，规则为offset 10000 - "17000:17000"

    # 挂载数据卷，用于宿主机和容器共享文件，格式为宿主机目录:容器内部目录

    volumes:

      - ./data/7001:/data
      - ./cluster-config/redis-node-7001.conf:/usr/local/etc/redis/redis.conf

    # 覆盖容器启动后默认执行的命令。

    command: redis-server /usr/local/etc/redis/redis.conf




  redis-7002:

    # 服务的镜像名称或镜像ID。如果镜像在本地不存在，Compose将会尝试拉取镜像。

    image:  model.vnet.com/zhongzi/redis:6.2.6-alpine

    # 创建的容器名称

    container_name: redis-7002

    # 自启动

    restart: always

    # container内的root拥有真正的root权限。否则，container内的root只是外部的一个普通用户权限。

    privileged: true

    # 为容器设置环境变量：

    environment:

      - TZ=Asia/Shanghai

    # 端口映射，格式为宿主机端口:容器内部端口

    ports:

      - "7002:7002"

      - "17002:17002"

    # 注意：这里记得打开集群总线端口，规则为offset 10000 - "17000:17000"

    # 挂载数据卷，用于宿主机和容器共享文件，格式为宿主机目录:容器内部目录

    volumes:

      - ./data/7002:/data
      - ./cluster-config/redis-node-7002.conf:/usr/local/etc/redis/redis.conf

    # 覆盖容器启动后默认执行的命令。

    command: redis-server /usr/local/etc/redis/redis.conf


