components: {}
info:
  title: RoutesExport
  version: 3.0.0
openapi: 3.0.0
paths:
  /fastapis/dataservice/v1/{params}:
    connect:
      operationId: apis_dataserviceCONNECT
      parameters:
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
      requestBody: {}
      responses:
        default:
          description: ''
      x-apisix-enable_websocket: false
      x-apisix-id: '554646082223605350'
      x-apisix-labels:
        API_VERSION: V1.0.0
        app: apis
      x-apisix-priority: 0
      x-apisix-status: 1
      x-apisix-upstream:
        nodes:
          - host: 192.168.33.35
            port: 7734
            weight: 1
        timeout:
          connect: 600
          send: 600
          read: 600
        type: roundrobin
        scheme: http
        pass_host: pass
        keepalive_pool:
          idle_timeout: 60
          requests: 1000
          size: 320
    delete:
      operationId: apis_dataserviceDELETE
      parameters:
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
      requestBody: {}
      responses:
        default:
          description: ''
      x-apisix-enable_websocket: false
      x-apisix-id: '554646082223605350'
      x-apisix-labels:
        API_VERSION: V1.0.0
        app: apis
      x-apisix-priority: 0
      x-apisix-status: 1
      x-apisix-upstream:
        nodes:
          - host: 192.168.33.35
            port: 7734
            weight: 1
        timeout:
          connect: 600
          send: 600
          read: 600
        type: roundrobin
        scheme: http
        pass_host: pass
        keepalive_pool:
          idle_timeout: 60
          requests: 1000
          size: 320
    get:
      operationId: apis_dataserviceGET
      parameters:
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
      requestBody: {}
      responses:
        default:
          description: ''
      x-apisix-enable_websocket: false
      x-apisix-id: '554646082223605350'
      x-apisix-labels:
        API_VERSION: V1.0.0
        app: apis
      x-apisix-priority: 0
      x-apisix-status: 1
      x-apisix-upstream:
        nodes:
          - host: 192.168.33.35
            port: 7734
            weight: 1
        timeout:
          connect: 600
          send: 600
          read: 600
        type: roundrobin
        scheme: http
        pass_host: pass
        keepalive_pool:
          idle_timeout: 60
          requests: 1000
          size: 320
    head:
      operationId: apis_dataserviceHEAD
      parameters:
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
      requestBody: {}
      responses:
        default:
          description: ''
      x-apisix-enable_websocket: false
      x-apisix-id: '554646082223605350'
      x-apisix-labels:
        API_VERSION: V1.0.0
        app: apis
      x-apisix-priority: 0
      x-apisix-status: 1
      x-apisix-upstream:
        nodes:
          - host: 192.168.33.35
            port: 7734
            weight: 1
        timeout:
          connect: 600
          send: 600
          read: 600
        type: roundrobin
        scheme: http
        pass_host: pass
        keepalive_pool:
          idle_timeout: 60
          requests: 1000
          size: 320
    options:
      operationId: apis_dataserviceOPTIONS
      parameters:
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
      requestBody: {}
      responses:
        default:
          description: ''
      x-apisix-enable_websocket: false
      x-apisix-id: '554646082223605350'
      x-apisix-labels:
        API_VERSION: V1.0.0
        app: apis
      x-apisix-priority: 0
      x-apisix-status: 1
      x-apisix-upstream:
        nodes:
          - host: 192.168.33.35
            port: 7734
            weight: 1
        timeout:
          connect: 600
          send: 600
          read: 600
        type: roundrobin
        scheme: http
        pass_host: pass
        keepalive_pool:
          idle_timeout: 60
          requests: 1000
          size: 320
    patch:
      operationId: apis_dataservicePATCH
      parameters:
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
      requestBody: {}
      responses:
        default:
          description: ''
      x-apisix-enable_websocket: false
      x-apisix-id: '554646082223605350'
      x-apisix-labels:
        API_VERSION: V1.0.0
        app: apis
      x-apisix-priority: 0
      x-apisix-status: 1
      x-apisix-upstream:
        nodes:
          - host: 192.168.33.35
            port: 7734
            weight: 1
        timeout:
          connect: 600
          send: 600
          read: 600
        type: roundrobin
        scheme: http
        pass_host: pass
        keepalive_pool:
          idle_timeout: 60
          requests: 1000
          size: 320
    post:
      operationId: apis_dataservicePOST
      parameters:
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
      requestBody: {}
      responses:
        default:
          description: ''
      x-apisix-enable_websocket: false
      x-apisix-id: '554646082223605350'
      x-apisix-labels:
        API_VERSION: V1.0.0
        app: apis
      x-apisix-priority: 0
      x-apisix-status: 1
      x-apisix-upstream:
        nodes:
          - host: 192.168.33.35
            port: 7734
            weight: 1
        timeout:
          connect: 600
          send: 600
          read: 600
        type: roundrobin
        scheme: http
        pass_host: pass
        keepalive_pool:
          idle_timeout: 60
          requests: 1000
          size: 320
    put:
      operationId: apis_dataservicePUT
      parameters:
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
      requestBody: {}
      responses:
        default:
          description: ''
      x-apisix-enable_websocket: false
      x-apisix-id: '554646082223605350'
      x-apisix-labels:
        API_VERSION: V1.0.0
        app: apis
      x-apisix-priority: 0
      x-apisix-status: 1
      x-apisix-upstream:
        nodes:
          - host: 192.168.33.35
            port: 7734
            weight: 1
        timeout:
          connect: 600
          send: 600
          read: 600
        type: roundrobin
        scheme: http
        pass_host: pass
        keepalive_pool:
          idle_timeout: 60
          requests: 1000
          size: 320
    trace:
      operationId: apis_dataserviceTRACE
      parameters:
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
      requestBody: {}
      responses:
        default:
          description: ''
      x-apisix-enable_websocket: false
      x-apisix-id: '554646082223605350'
      x-apisix-labels:
        API_VERSION: V1.0.0
        app: apis
      x-apisix-priority: 0
      x-apisix-status: 1
      x-apisix-upstream:
        nodes:
          - host: 192.168.33.35
            port: 7734
            weight: 1
        timeout:
          connect: 600
          send: 600
          read: 600
        type: roundrobin
        scheme: http
        pass_host: pass
        keepalive_pool:
          idle_timeout: 60
          requests: 1000
          size: 320
  /fastapis/pluginservice/v1/{params}:
    connect:
      operationId: apis_pluginserviceCONNECT
      parameters:
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
      requestBody: {}
      responses:
        default:
          description: ''
      x-apisix-enable_websocket: false
      x-apisix-id: '554646004243105382'
      x-apisix-labels:
        API_VERSION: V1.0.0
        app: apis
      x-apisix-priority: 0
      x-apisix-status: 1
      x-apisix-upstream:
        nodes:
          - host: 192.168.33.35
            port: 7735
            weight: 1
        timeout:
          connect: 600
          send: 600
          read: 600
        type: roundrobin
        scheme: http
        pass_host: pass
        keepalive_pool:
          idle_timeout: 60
          requests: 1000
          size: 320
    delete:
      operationId: apis_pluginserviceDELETE
      parameters:
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
      requestBody: {}
      responses:
        default:
          description: ''
      x-apisix-enable_websocket: false
      x-apisix-id: '554646004243105382'
      x-apisix-labels:
        API_VERSION: V1.0.0
        app: apis
      x-apisix-priority: 0
      x-apisix-status: 1
      x-apisix-upstream:
        nodes:
          - host: 192.168.33.35
            port: 7735
            weight: 1
        timeout:
          connect: 600
          send: 600
          read: 600
        type: roundrobin
        scheme: http
        pass_host: pass
        keepalive_pool:
          idle_timeout: 60
          requests: 1000
          size: 320
    get:
      operationId: apis_pluginserviceGET
      parameters:
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
      requestBody: {}
      responses:
        default:
          description: ''
      x-apisix-enable_websocket: false
      x-apisix-id: '554646004243105382'
      x-apisix-labels:
        API_VERSION: V1.0.0
        app: apis
      x-apisix-priority: 0
      x-apisix-status: 1
      x-apisix-upstream:
        nodes:
          - host: 192.168.33.35
            port: 7735
            weight: 1
        timeout:
          connect: 600
          send: 600
          read: 600
        type: roundrobin
        scheme: http
        pass_host: pass
        keepalive_pool:
          idle_timeout: 60
          requests: 1000
          size: 320
    head:
      operationId: apis_pluginserviceHEAD
      parameters:
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
      requestBody: {}
      responses:
        default:
          description: ''
      x-apisix-enable_websocket: false
      x-apisix-id: '554646004243105382'
      x-apisix-labels:
        API_VERSION: V1.0.0
        app: apis
      x-apisix-priority: 0
      x-apisix-status: 1
      x-apisix-upstream:
        nodes:
          - host: 192.168.33.35
            port: 7735
            weight: 1
        timeout:
          connect: 600
          send: 600
          read: 600
        type: roundrobin
        scheme: http
        pass_host: pass
        keepalive_pool:
          idle_timeout: 60
          requests: 1000
          size: 320
    options:
      operationId: apis_pluginserviceOPTIONS
      parameters:
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
      requestBody: {}
      responses:
        default:
          description: ''
      x-apisix-enable_websocket: false
      x-apisix-id: '554646004243105382'
      x-apisix-labels:
        API_VERSION: V1.0.0
        app: apis
      x-apisix-priority: 0
      x-apisix-status: 1
      x-apisix-upstream:
        nodes:
          - host: 192.168.33.35
            port: 7735
            weight: 1
        timeout:
          connect: 600
          send: 600
          read: 600
        type: roundrobin
        scheme: http
        pass_host: pass
        keepalive_pool:
          idle_timeout: 60
          requests: 1000
          size: 320
    patch:
      operationId: apis_pluginservicePATCH
      parameters:
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
      requestBody: {}
      responses:
        default:
          description: ''
      x-apisix-enable_websocket: false
      x-apisix-id: '554646004243105382'
      x-apisix-labels:
        API_VERSION: V1.0.0
        app: apis
      x-apisix-priority: 0
      x-apisix-status: 1
      x-apisix-upstream:
        nodes:
          - host: 192.168.33.35
            port: 7735
            weight: 1
        timeout:
          connect: 600
          send: 600
          read: 600
        type: roundrobin
        scheme: http
        pass_host: pass
        keepalive_pool:
          idle_timeout: 60
          requests: 1000
          size: 320
    post:
      operationId: apis_pluginservicePOST
      parameters:
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
      requestBody: {}
      responses:
        default:
          description: ''
      x-apisix-enable_websocket: false
      x-apisix-id: '554646004243105382'
      x-apisix-labels:
        API_VERSION: V1.0.0
        app: apis
      x-apisix-priority: 0
      x-apisix-status: 1
      x-apisix-upstream:
        nodes:
          - host: 192.168.33.35
            port: 7735
            weight: 1
        timeout:
          connect: 600
          send: 600
          read: 600
        type: roundrobin
        scheme: http
        pass_host: pass
        keepalive_pool:
          idle_timeout: 60
          requests: 1000
          size: 320
    put:
      operationId: apis_pluginservicePUT
      parameters:
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
      requestBody: {}
      responses:
        default:
          description: ''
      x-apisix-enable_websocket: false
      x-apisix-id: '554646004243105382'
      x-apisix-labels:
        API_VERSION: V1.0.0
        app: apis
      x-apisix-priority: 0
      x-apisix-status: 1
      x-apisix-upstream:
        nodes:
          - host: 192.168.33.35
            port: 7735
            weight: 1
        timeout:
          connect: 600
          send: 600
          read: 600
        type: roundrobin
        scheme: http
        pass_host: pass
        keepalive_pool:
          idle_timeout: 60
          requests: 1000
          size: 320
    trace:
      operationId: apis_pluginserviceTRACE
      parameters:
        - description: params in path
          in: path
          name: params
          required: true
          schema:
            type: string
      requestBody: {}
      responses:
        default:
          description: ''
      x-apisix-enable_websocket: false
      x-apisix-id: '554646004243105382'
      x-apisix-labels:
        API_VERSION: V1.0.0
        app: apis
      x-apisix-priority: 0
      x-apisix-status: 1
      x-apisix-upstream:
        nodes:
          - host: 192.168.33.35
            port: 7735
            weight: 1
        timeout:
          connect: 600
          send: 600
          read: 600
        type: roundrobin
        scheme: http
        pass_host: pass
        keepalive_pool:
          idle_timeout: 60
          requests: 1000
          size: 320
