global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'my_custom_target'
    static_configs:
      - targets: ['172.22.220.21:8020']