services:
  ntp:
    image: dockurr/chrony:4.7
    #image: model.vnet.com/zhongzi/chronyd:0.7.0
    container_name: ntp
    restart: always
    read_only: true
    tmpfs:
      - /etc/chrony:rw,mode=1750,uid=100,gid=101
      - /run/chrony:rw,mode=1750,uid=100,gid=101
      - /var/lib/chrony:rw,mode=1750,uid=100,gid=101
    ports:
      - 123:123/udp
    # if you'd like chronyd to synchronize your hosts clock, uncomment these settings
    user: "0:0"
    cap_add:
      - SYS_TIME
    devices:
      - /dev/ptp0:/dev/ptp0
    environment:
      - NTP_SERVERS=ntp.ntsc.ac.cn,pool.ntp.org,ntp.aliyun.com
      - LOG_LEVEL=5
      - TZ=Asia/Shanghai  # 设置时区为上海
      # - NOCLIENTLOG=true
      #- ENABLE_NTS=true
      #- ENABLE_SYSCLK=true